### ISSUE TITLE
Error - UnboundLocalError: local variable 'uuid' referenced before assignment

### ISSUE THREAD

**Issue by sakbioonline** [ghammad/pyActigraphy#142]
Hello @ghammad,

Getting the above error when using the read_raw method for the Reposnic Actigraphy.

import pyActigraphy
import os

fpath = os.path.join('Actigraphy', 'E004.csv')
raw = pyActigraphy.io.read_raw_rpx(fpath)

I've attached my sample file.

[E004.csv](https://github.com/ghammad/pyActigraphy/files/13267052/E004.csv)

Platform: Windows 11
PyActigraphy Version: 1.2.1

Best regards,
Abiola Saka

**Comment by ghammad** [comment]
Hello @sakbioonline 

Thank you for using the package and reporting this issue.

I had a look at your file and contrary to other Respironics files, its header does not contain any information about the device (type, uuid, etc). As the code tries to use this info, it fails with the error message you face.

Did you edit your file in any way? I suspect so since the the 3rd/4th line in your header are supposed (at least in the Respironics files I have seen so far) to be in a specific header section where one would actually also find the device type and uuid.

If you did edit the file, try to use the original file with pyactigraphy:
```python
raw = read_raw_rpx('/Users/ghammad/Downloads/E004.csv',language='ENG_UK')
```

(Since the header is written in UK English, explicitly set it in the reader function so that it knows which convention it should use for the data time format: day first!)

Hope that helps.

Greg

**Comment by sakbioonline** [comment]
@ghammad Thanks for your prompt response and resolution. Not at all, I did not edit the file. Can you show me how the sample header for a working file looks like, please?

**Comment by ghammad** [comment]
Hello @sakbioonline 

Sorry for not having answered earlier. I do hope that you found a way through this issue in the meantime.

For the record, you can find an example of Respironic Actiwatch in the [tests/data](https://github.com/ghammad/pyActigraphy/blob/master/pyActigraphy/tests/data) directory of pyActigraphy.

Here are the first 50 lines of an Actiwatch 2 UK [file](https://github.com/ghammad/pyActigraphy/blob/master/pyActigraphy/tests/data/test_sample_rpx_eng.csv):

```
"Actiware Export File  (Version 05.00 )"
"Filename:",""
"Analysis Name:",""


"-------------------- Subject Properties--------------------"

"Identity:","TEST_SAMPLE_UK"
"Initials:","*"
"Full Name:","*"
"Street Address:","*"
"City State Zip Country:","*"
"Phone:","*"
"Gender:","*"
"Date of Birth:","01/01/1911"
"Age (at time of export file creation):","100","years"
"Age (at start of data collection):","100","years"


"----------------- Actiwatch Data Properties ----------------"

"Actiwatch Type:","Actiwatch 2"
"Data Collection Start Date:","04/07/2015"
"Data Collection Start Time:","09:45:00"
"Data Collection End Date:","11/07/2015"
"Data Collection End Time:","09:44:30"
"Logging Mode:","Activity and Photopic Light"
"Time Zone:","(UTC) Dublin, Edinburgh, Lisbon, London"
"Time Zone Offset:","+01:00","hours:minutes"
"Epoch Length:","30","seconds",""
"Number of Data Samples:","20160","samples"
"Number of Data Samples per Day:","2880","samples per day"
"Number of Days:","10.10","days"
"Battery Installed Date:","01/01/1902"
"Number of Processor Resets:","0"
"Actiwatch Serial Number:","AXXXUK"
"Actiwatch Firmware Version:","01.01.0010"
"Activity Calibration Factor:","83"
"White Calibration Factor:","23058"
"Red Calibration Factor:","Not Applicable"
"Green Calibration Factor:","Not Applicable"
"Blue Calibration Factor:","Not Applicable"
"Clear Calibration Factor:","Not Applicable"
"Scoring Mode:","Not Applicable"
"Parameter A:","Not Applicable"
"Parameter B:","Not Applicable"
```

Closing the issue now but feel free to reopen it and share any potential solution you may have found.

Cheers,

Greg
