### ISSUE TITLE
Issue with the reading of some actigraph

### ISSUE THREAD

**Issue by amondino** [ghammad/pyActigraphy#78]
Hi! The actical solution worked amazing, but I am having some issues with some of the actigraph files
It is saying this:
DatabaseError: Execution failed on sql 'SELECT state, timeStamp FROM capsense': no such table: [capsense](url)

Thanks!
Ale

**Comment by ghammad** [comment]
Hello @amondino

Indeed, the "wear" sensor is either no present on some models or simply not configured in your recordings.

It has been fixed in this [commit](bed6978bcdacd88b338926e77fdfd67dbfb5099e).

Until I make a new release with this fix, may I ask you to use the "develop" branch? Follow the info "for developers" in the [installation](https://github.com/ghammad/pyActigraphy#installation) section.

NB: just a side remark, for the future, the "wear" sensor is extremely handy as it can be used to create a "non-wear" mask. Instead of manually specifying the non-wear periods in a mask file.

**Comment by amondino** [comment]
Thanks Dr. Hammad, but the commit link is not working, could you please include it again?
Thanks
Alejandra

**Comment by ghammad** [comment]
Hi @amondino ; it is fixed. But just to be sure: it is a link to a commit that shows the issue has been fixed. For your own info.

Now, you need to use the code in the "develop" branch. You will find the info about how to use the code under "For developers" in the installation section (cf. previous message).

HTH.

Greg

**Comment by ghammad** [comment]
Closing now as it has been fixed.
