### ISSUE TITLE
Mismatch in code vs documentation

### ISSUE THREAD

**Issue by alexandraingvars** [ghammad/pyActigraphy#96]
Hello Grégory,
We are a couple of BSc students working with ActTrust and ActTrust 2 wristbands for a research. We noticed a mismatch in the documentation and the code. For example, in the documentation the Cole-Kripke (CK) function can take the parameters "settings" but the code does not have that parameter. Is it possible to update the documentation?

Thanks!
Alexandra

**Comment by ghammad** [comment]
Hello @alexandraingvars. Looking at the doc is usually a good practice. But indeed, there is a mismatch between the code and the doc in this case. You made me realise that I accidentally published the documentation relative to the "develop" branch instead of the "master" branch. Sorry for the confusion. I will reset the documentation to the one associated to the v1.0.

If you need to be able to use different (or at least the appropriate) settings for the CK algorithm, follow the installation instructions for developers (https://ghammad.github.io/pyActigraphy/index.html#installation). By using the 'develop' branch, you will be able to use the latest features/improvements of pyActigraphy, including the different CK settings.

Ultimately, if you need to see the documentation for a specific function, use the 'help' command:
```python
import pyActigraphy
help(pyActigraphy.sleep.ScoringMixin.CK)
```
It will display the actual documentation for the CK function. No risk of mismatch in this case.

Hope that helps.

Good luck with your analysis and happy actigraphing.

Grégory
